In [2]:
import numpy as np # numerical computation
import pandas as pd # data wrangling
import matplotlib.pyplot as plt # plotting package
import matplotlib as mpl # add'1 plotting functionality
mpl.rcParams['figure.dpi'] = 400 # high res figures

In [3]:
medal_distribution_2024 = pd.read_csv('../data/raw/medalists_data_raw.csv')
medal_distribution_2024.head()

,medal_date,medal_type,medal_code,name,gender,country_code,country,country_long,nationality_code,nationality,...,team,team_gender,discipline,event,event_type,url_event,birth_date,code_athlete,code_team,is_medallist
0,2024-07-27,Gold Medal,1.0,EVENEPOEL Remco,Male,BEL,Belgium,Belgium,BEL,Belgium,...,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,2000-01-25,1903136,NaN,True
1,2024-07-27,Silver Medal,2.0,GANNA Filippo,Male,ITA,Italy,Italy,ITA,Italy,...,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1996-07-25,1923520,NaN,True
2,2024-07-27,Bronze Medal,3.0,van AERT Wout,Male,BEL,Belgium,Belgium,BEL,Belgium,...,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1994-09-15,1903147,NaN,True
3,2024-07-27,Gold Medal,1.0,BROWN Grace,Female,AUS,Australia,Australia,AUS,Australia,...,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1992-07-07,1940173,NaN,True
4,2024-07-27,Silver Medal,2.0,HENDERSON Anna,Female,GBR,Great Britain,Great Britain,GBR,Great Britain,...,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1998-11-14,1912525,NaN,True

In [4]:
medal_distribution_2024 = medal_distribution_2024[['country', 'medal_type']]
medal_distribution_2024.head()

         country    medal_type
0        Belgium    Gold Medal
1          Italy  Silver Medal
2        Belgium  Bronze Medal
3      Australia    Gold Medal
4  Great Britain  Silver Medal

In [5]:
medal_distribution_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2315 entries, 0 to 2314
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     2315 non-null   object
 1   medal_type  2315 non-null   object
dtypes: object(2)
memory usage: 36.3+ KB

In [6]:
medal_distribution_2024.set_index('country', inplace=True)
medal_distribution_2024.head()

                 medal_type
country
Belgium          Gold Medal
Italy          Silver Medal
Belgium        Bronze Medal
Australia        Gold Medal
Great Britain  Silver Medal

In [7]:
folder_path = '../data/processed/'
file_name = 'medal_distribution_2024_processed.csv'
full_path = folder_path + file_name

medal_distribution_2024.to_csv(full_path)

In [8]:
world_population_gdp_2024 = pd.read_csv("../data/raw/world_gdp_data_raw.csv")
world_population_gdp_2024.head()

,population,id,imfGDP,unGDP,country,gdpPerCapita,continent,rank
0,345426571,840,2.878108e+13,25744100000000,United States,83320.399808,North America,1
1,1419321278,156,1.853263e+13,17963170521080,China,13057.388970,Asia,2
2,84552242,276,4.591100e+12,4076923618912,Germany,54298.974118,Europe,3
3,123753041,392,4.110450e+12,4232173916087,Japan,33214.941361,Asia,4
4,1450935791,356,3.937010e+12,3465541446546,India,2713.428137,Asia,5

In [9]:
world_population_gdp_2024 = world_population_gdp_2024[['country', 'population', 'gdpPerCapita']]
world_population_gdp_2024.head()

         country  population  gdpPerCapita
0  United States   345426571  83320.399808
1          China  1419321278  13057.388970
2        Germany    84552242  54298.974118
3          Japan   123753041  33214.941361
4          India  1450935791   2713.428137

In [10]:
world_population_gdp_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       212 non-null    object
 1   population    212 non-null    int64
 2   gdpPerCapita  212 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 5.1+ KB

In [11]:
world_population_gdp_2024.set_index('country', inplace=True)
world_population_gdp_2024.head()

               population  gdpPerCapita
country
United States   345426571  83320.399808
China          1419321278  13057.388970
Germany          84552242  54298.974118
Japan           123753041  33214.941361
India          1450935791   2713.428137

In [12]:
folder_path = '../data/processed/'
file_name = 'world_population_gdp_2024_processed.csv'
full_path = folder_path + file_name

world_population_gdp_2024.to_csv(full_path)